project:
  type: website
  output-dir: _site

website:
  title: "The Sett"
  navbar:
    title: false
    search: true
    logo: graphics/Banner.png
    logo-href: http://buffalobadger.github.io
    left:
      - text: "Reaction Engineering Basics"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "SCoRE"
        href: file:///Users/lund/Projects/Kinetics/SCoRE/_site/index.html
      - text: "ToTaL Engineering"
        href: file:///Users/lund/Projects/ToTaL_Engineering/_site/index.html
      - text: "The Sett"
        href: index.qmd
      - text: "About"
        href: file:///Users/lund/Projects/BuffaloBadger.github.io/_site/about.html 
  search:
    location: navbar
    type: overlay
  page-footer:
    background: light
    right: 
      - text: Copyright 2024, Carl Lund 
  favicon: graphics/BuffaloBadger_16_16.png
  sidebar:
    style: floating
    search: false
    collapse-level: 1
    contents: 
      - text: "Welcome"
        href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
